/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hallmanagement.ui;
import com.hallmanagement.dao.MenuDAOImpl;
import com.hallmanagement.model.MenuItem;
import java.util.List;

/**
 *
 * @author ABN TECHNOLOGY
 */
public class ManageMenuFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageMenuFrame.class.getName());

    /**
     * Creates new form ManageMenuFrame
     */
 public ManageMenuFrame() {
    initComponents();
    loadWeeklyMenu();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        saveChangesButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Saturday", null, null, null},
                {"Sunday", null, null, null},
                {"Monday", null, null, null},
                {"Tuesday", null, null, null},
                {"Wednesday", null, null, null},
                {"Thursday", null, null, null},
                {"Friday", null, null, null}
            },
            new String [] {
                "Day", "Breakfast", "Lunch", "Dinner"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        saveChangesButton.setText("Save Changes");
        saveChangesButton.addActionListener(this::saveChangesButtonActionPerformed);

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        titleLabel.setText("Weekly Menu Management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveChangesButton)
                            .addComponent(backButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(titleLabel)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(saveChangesButton)
                        .addGap(18, 18, 18)
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(titleLabel)
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
                                                        
    MenuDAOImpl dao = new MenuDAOImpl();

    boolean allUpdated = true;

    for (int i = 0; i < jTable1.getRowCount(); i++) {

        String day = jTable1.getValueAt(i, 0).toString();
        String breakfast = jTable1.getValueAt(i, 1).toString();
        String lunch = jTable1.getValueAt(i, 2).toString();
        String dinner = jTable1.getValueAt(i, 3).toString();

        boolean updated = dao.updateDayMenu(
                day,
                breakfast,
                lunch,
                dinner
        );

        if (!updated) {
            allUpdated = false;
        }
    }

    if (allUpdated) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Weekly menu updated successfully!"
        );
    } else {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Some menu items could not be updated."
        );
    }
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
     AdminDashboard dashboard = new AdminDashboard();
dashboard.setVisible(true);
this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

   private void loadWeeklyMenu() {
    MenuDAOImpl dao = new MenuDAOImpl();
    List<MenuItem> menuList = dao.getWeeklyMenu();

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

    model.setRowCount(0);

    for (MenuItem item : menuList) {
        model.addRow(new Object[]{
            item.getDayName(),
            item.getBreakfastItem(),
            item.getLunchItem(),
            item.getDinnerItem()
        });
    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageMenuFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton saveChangesButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
