/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hallmanagement.ui;
import com.hallmanagement.dao.MenuDAOImpl;
import com.hallmanagement.model.MealPrice;

/**
 *
 * @author ABN TECHNOLOGY
 */
public class ManagePriceFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManagePriceFrame.class.getName());

    /**
     * Creates new form ManagePriceFrame
     */
    public ManagePriceFrame() {
        initComponents();
         loadMealPrices();
    }
    private void loadMealPrices() {

    MenuDAOImpl dao = new MenuDAOImpl();

    MealPrice price = dao.getMealPrices();

    breakfastPriceField.setText(String.valueOf(price.getBreakfastPrice()));
    lunchPriceField.setText(String.valueOf(price.getLunchPrice()));
    dinnerPriceField.setText(String.valueOf(price.getDinnerPrice()));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        breakfastLabel = new javax.swing.JLabel();
        lunchLabel = new javax.swing.JLabel();
        breakfastPriceField = new javax.swing.JTextField();
        lunchPriceField = new javax.swing.JTextField();
        dinnerPriceField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dinnerLabel = new javax.swing.JLabel();
        savePriceButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("Manage Meal Prices");

        breakfastLabel.setText("Breakfast Price:");

        lunchLabel.setText("Lunch Price:");

        breakfastPriceField.addActionListener(this::breakfastPriceFieldActionPerformed);

        lunchPriceField.addActionListener(this::lunchPriceFieldActionPerformed);

        dinnerLabel.setText("Dinner Price:");

        savePriceButton.setText("Save Prices");
        savePriceButton.addActionListener(this::savePriceButtonActionPerformed);

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dinnerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dinnerPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lunchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lunchPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(breakfastLabel)
                        .addGap(18, 18, 18)
                        .addComponent(breakfastPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savePriceButton)
                    .addComponent(backButton))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titleLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(breakfastLabel)
                            .addComponent(breakfastPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(savePriceButton)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lunchLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lunchPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backButton)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dinnerPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(dinnerLabel))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void breakfastPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakfastPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_breakfastPriceFieldActionPerformed

    private void lunchPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lunchPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lunchPriceFieldActionPerformed

    private void savePriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePriceButtonActionPerformed
      try {

    double breakfast = Double.parseDouble(breakfastPriceField.getText());
    double lunch = Double.parseDouble(lunchPriceField.getText());
    double dinner = Double.parseDouble(dinnerPriceField.getText());

    MenuDAOImpl dao = new MenuDAOImpl();

    boolean updated = dao.updateMealPrices(
            breakfast,
            lunch,
            dinner
    );

    if (updated) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Meal prices updated successfully!"
        );
    } else {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Meal prices could not be updated."
        );
    }

} catch (NumberFormatException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please enter valid numbers for all prices."
    );
}
    }//GEN-LAST:event_savePriceButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       
    AdminDashboard dashboard = new AdminDashboard();
    dashboard.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManagePriceFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel breakfastLabel;
    private javax.swing.JTextField breakfastPriceField;
    private javax.swing.JLabel dinnerLabel;
    private javax.swing.JTextField dinnerPriceField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lunchLabel;
    private javax.swing.JTextField lunchPriceField;
    private javax.swing.JButton savePriceButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
